config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'posts#index'
  #nested resource(recurso aninhado)
  resources :posts do
  	resources :comments # os comentarios precisam dos posts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :name, :comment, presence:true #nome e comentario devem estar presentes
	validates_length_of :comment , maximum:200 #o comentario deve ter no maximo 200 caracteres
  	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	acts_as_paranoid
	validates :titulo, :conteudo, :data, presence: true  #os campos titulo, conteudo e data sao obrigatorios estarem presentes
	has_many :comments , dependent: :destroy #um post pode ter muitos comentarios, mas se esse post for deletado os comentarios serao deletados tbm
	validates_length_of :titulo, maximum: 200 #o campo titulo pode ter no maximo 200 caracteres
	validates_length_of :conteudo, maximum: 10000 #o campo conteudo pode ter no maximo 600 caracteres

 	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/ #enviar apenas imagem
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def index
		@post= Post.find(params[:post_id])
		@comments = @post.comments
	end 

	#Novo comentario do post que se quer comentar
	def new
		@post = Post.find(params[:post_id])
		@comment = @post.comments.new 
	end

	def create
		@post=Post.find(params[:post_id])
		@comment=@post.comments.new(comment_params)
		if @comment.save #se salvo com sucesso
			redirect_to post_comments_path(@post), notice: 'Comentário gravado com sucesso!'
		else
			render :new
		end
	end

	private
		def comment_params
			params.require(:comment).permit(:name, :comment)
		end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show] #Devise(o usuario deve se autenticar) Se nao estiver logado ele so podera fazer comentarios

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    respond_to do |format|
      format.html
      format.xlsx
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save #Se as informaçoes forem salvas no banco com sucesso
        format.html { redirect_to @post, notice: 'Post criado com sucesso.' } #redireciona para o proprio post
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new } #Senao redenriza novamente o formulario para poder colocar as informaçoes novamente
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path :notice => "Seu post foi deletado com sucesso"
    #@post.destroy
    #respond_to do |format|
     # format.html { redirect_to posts_url, method: :delete, notice: 'Post excluído com sucesso.' }
      #format.json { head :no_content }
    #end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:titulo, :conteudo, :data, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@post, @comment]) do |f| %>
		<p class="form-group">
			<%= f.label :Nome %><br/>
			<%= f.text_field :name, autofocus: true, class:"form-control" %>
		</p>
		<p class="form-group">
		<%= f.label :Comentário %><br/>
		<%= f.text_area :comment, placeholder:"Escreva seu comentário..." , class:"form-control" %>
		</p>
		<p>
			<%= f.submit class:'btn btn-primary' %>
			<%= link_to 'Cancelar', root_path , class: 'btn btn-default' %>
		</p>
	<% end %>

app/views/comments/index.html.erb
<div class="container">
<% if @post.comments.size > 0 %>
	<div class="jumbotron">
		<ul>
			<% @comments.each do |comment| %>
			<li>
				<p>
					<%= comment.name %> <small class="small_font"> - <%= time_ago_in_words(comment.created_at) %> atrás</small>
				</p>
				<p>
					<%= comment.comment %>
				</p>
			</li>
			<% end %>
		</ul>
	</div>
	<% else %>
	<div class="jumbotron">
		<h3>Não existem comentários!</h3>
	</div>
	<% end %>

	<%= link_to posts_path , class:'btn btn-link' do %>
	<i class="glyphicon glyphicon-home"> Posts</i>
	<% end %>
</div>

app/views/comments/new.html.erb
<div class='container'>
<div class="panel panel-default">
	<div class="panel-heading">
		<h2>Criando novo Comentário</h2>
	</div>
	<div class="panel-body">

	<%= render 'form' %>
	
	</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Projeto</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
</head>
<body>

<!-- Barra de navegaçao -->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to image_tag('blog.jpg', size:'30', alt:'blog'), root_path, class:'navbar-brand' %>
      <%= link_to 'Posts', root_path, class:'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Posts', root_path %></li>

        <!-- Devise -->
        <% if user_signed_in? %> <!-- Se usuario estiver logado -->
    			<li>Logado com <%= current_user.email %></li>
    			<li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
		<% else %> <!-- Senao -->
			    <li><%= link_to "Cadastro de novo usuário", new_user_registration_path %></li>
			    <li><%= link_to "Logar", new_user_session_path %></li>
		<% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  
<%= yield %>
  
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :multipart => true } do |f| %>
  <!-- Codigo para mostrar os erros -->
  <% if @post.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <ul>
        <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    
  <!-- formulario para criaçao de um novo post -->
  <p class="form-group">
    <%= f.label :título %>
    <%= f.text_field :titulo , class:"form-control" %>
  </p>

  <p class="form-group">
    <%= f.label :conteúdo %>
    <%= f.text_area :conteudo, cols:20, rows:5, class:"form-control" %>
  </p>

  <p class="form-group">
    <%= f.label :data %>
    <%= f.date_select :data, class:"form-control" %>
  </p>

  <div class="field">
    <%= f.label :imagem %>
    <%= f.file_field :avatar %>
  </div>


  <p>
    <%= f.submit class:'btn btn-primary' %>
    <%= link_to 'Cancelar', root_path , class: 'btn btn-default' %> <!-- link para cancelar uma nova postagem e voltar a pagina inicial -->
  </p>
<% end %>

app/views/posts/edit.html.erb
<div class='container'> <!-- centralizar o painel -->
<div class="panel panel-default">
  <div class="panel-heading">
  	<h2>Editando Post</h2>
  </div>
  <div class="panel-body">
    <%= render 'form', post: @post %>
  </div>
</div>
</div>

<!-- links para mostrar ou voltar na pagina de editar post -->
<%= link_to 'Mostrar', @post %> |
<%= link_to 'Voltar', posts_path %>

app/views/posts/index.html.erb
<h1>Blog Notícias Digitais da Renata</h1>

<!-- Page Content -->
  <div class="container">

    <!-- Page Heading -->
    <div class="row"
      <div class="col-lg-12">
        <h4 class="page-header"><%= pluralize(@posts.size, "Postagem", "Postagens") %>
        <small class="novo_post" ><%= link_to "Novo Post", new_post_path, class: 'btn btn-warning' %></small>  <!-- link novo post na pagina inicial -->
        </h4>
      </div>
    </div>
    <!-- /.row -->

    <!-- Project One -->
    <% @posts.reverse.each do |post| %>  <!-- uso do reverse para que os posts mais recentes apareçam por cima -->
    <div class="row">
      <div class="col-nd-2">
        <h4><%= link_to post.titulo, post %></h4>  <!-- link para os titulos dos posts -->
        <p><%= image_tag post.avatar.url(:thumb) %></p>
      </div>
      
      <div class="col-nd-7">
        <p><%= truncate(post.conteudo, lenght: 15 , separator: '') %></p>
        <h5><%=h post.data.to_s(:long) %></h5>  <!-- data inserida como string -->
      </div>
    </div>
    <hr>

<% end %>

<p>
  <%= link_to "Download Excel", posts_path(format: :xlsx), class: 'btn btn-danger'%>  <!-- link para download do excel -->
</p>

app/views/posts/new.html.erb
<div class='container'> <!-- centralizar o painel -->
<div class="panel panel-default">
  <div class="panel-heading">
  	<h2>Novo Post</h2>
  </div>
  <div class="panel-body">
    <%= render 'form', post: @post %>
  </div>
</div>
</div>

app/views/posts/show.html.erb
<div class="container">
<div class="jumbotron">
<p id="notice"><%= notice %></p>

<p>
  <strong>Título:</strong>
  <%= @post.titulo %>
</p>

<p>
  <strong>Conteúdo:</strong>
  <%= @post.conteudo %>
</p>

<p>
  <strong>Data:</strong>
  <%= @post.data.to_s(:long) %>
</p>

<p>
<strong>Imagem:</strong>
<%= image_tag @post.avatar.url(:thumb) %>
</p>

<%= link_to pluralize(@post.comments.size, 'Comentário', 'Comentários'), post_comments_path(@post) %> <!-- link para visualizaçao dos comentarios -->

<%= link_to 'Novo Comentário', new_post_comment_path(@post), class: 'btn btn-primary' %> <!-- link para inserir novo comentario -->

</div>

<!-- link para voltar para pagina inicial -->
<%= link_to posts_path , class:'btn btn-link' do %>
	<i class="glyphicon glyphicon-home"> Blog</i>
<% end %>

<!-- link para editar uma postagem -->
<%= link_to edit_post_path(@post), class:'btn btn-link' do %>
	<i class="glyphicon glyphicon-edit"> Editar</i>
<% end %>

<!-- link para deletar uma postagem -->
<%= link_to @post, :confirm => "Deseja apagar?", :method => :delete, class:'btn btn-link' do %>
	<i class="glyphicon glyphicon-remove-sign"> Deletar</i>
<% end %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Entrar", new_session_path(resource_name), class: 'btn btn-success' %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sair", new_registration_path(resource_name), class: 'btn btn-danger' %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Esqueceu sua senha?", new_password_path(resource_name)  %><br />
<% end -%> 

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Não recebeu instrução de confirmação?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Não recebeu instruções de desbloqueio?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Entrar com #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>